name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 01:00 CET (00:00 UTC) during Winter
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update this repos README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
