name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Ändern Sie den Namen des Branches, wenn nötig

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest

    steps:
      - name: Check if pusher is not 'github-actions[bot]'
        run: |
          if [ "$GITHUB_ACTOR" == "github-actions[bot]" ]; then
            echo "Pusher is 'github-actions[bot]', exiting."
            exit 0
          fi

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README using WakaTime
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"
          LOCALE: "en"
