name: Waka Readme

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: master
          TARGET_PATH: Readme.md
          BLOCKS: ->
          CODE_LANG: rust
          IGNORED_LANGUAGES: CSV Nix Riff INI ML OpenEdge go.mod  Script Apache Config Requirements.txt TypeScript Image (svg) reStructuredText Objective-C  OpenEdge ABL XML Batch INI textmate Roff Nix CSV

